import = ["~/.config/alacritty/kanagawa.toml"]

[colors]
draw_bold_text_with_bright_colors = false

[font.normal]
family = "Inconsolata"
style = "Regular"

[[keyboard.bindings]]
chars = "\u001Bf"
key = "Right"
mods = "Alt"

[[keyboard.bindings]]
chars = "\u001Bb"
key = "Left"
mods = "Alt"
